# Changes here will be overwritten by Copier
_commit: v2.0.3
_src_path: gh:lincc-frameworks/python-project-template
author_email: lp@irb.hr
author_name: Lovro Palaversa
create_example_module: true
custom_install: true
enforce_style: []
failure_notification: []
include_benchmarks: false
include_docs: true
include_notebooks: true
mypy_type_checking: none
package_name: photod
project_license: BSD
project_name: photod
project_organization: labastro-rbi
python_versions:
- '3.10'
- '3.11'
- '3.12'
